### ISSUE TITLE
Time not recorded for levels perfected without timer

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-an-atom#459]
**Test device**
Lenovo
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1339
If a level has been completed with full stars and without the timer, then turning on the timer does not record a best time when you play again.
**Steps to reproduce**
1. Play a game level and get full stars without the timer on
2. Turn on the timer
3. Play that same level again, again with perfect stars

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build an Atom‬
URL: https://phet-dev.colorado.edu/html/build-an-atom/1.9.0-dev.5/phet/build-an-atom_all_phet.html
Version: 1.9.0-dev.5 2025-12-16 17:09:26 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36
Language: en-US
Window: 1280x631
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
If you start with the timer on and perfect a level, then complete a level perfect without the timer, the best time seems to be erased and the above bug happens if you turn the timer back on.

**Comment by jbphet** [comment]
There were two things that were leading to incorrect behavior here.  One is that the `isNewBestTimeProperty` was never being set to `false` once a best time was recorded.  The other is that there was no check of whether the timer was enabled when recording the best time, which was leading to a value of zero being recorded, which could never be improved upon, and which the code for displaying the value was treating as 'falsey' and not displaying a value.

I think I have now fixed this, @KatieWoe please re-test on the main branch.

**Comment by Nancy-Salpepi** [comment]
@jbphet this was being worked on over in https://github.com/phetsims/vegas/issues/130. 
Not sure how your changes affect this.
@marlitas FYI.
 
I just tested and something is still broken. I'm not sure which commit might have caused it and whether it is BAA specific or part of vegas.
